name: Python Package

on:
  release:
    types: [published]
  push:
  workflow_dispatch:


permissions:
  contents: read

jobs:
  build_wheels:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Stub `setup.py` check
      # It will be generated during CMake run
      # https://github.com/pypa/cibuildwheel/issues/1139
      run: touch python/setup.py

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.7.0
      env:
        CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_28
        # installing packages in AlmaLinux is a quest
        # https://bugs.almalinux.org/view.php?id=208&nbn=3
        CIBW_BEFORE_ALL: >
          dnf install -y epel-release &&
          dnf module enable -y mariadb-devel &&
          dnf install -y $(grep "^[^#]" dependencies.txt) &&
          echo "need newer asio-devel version" &&
            curl -OL https://download.sourceforge.net/asio/asio-1.21.0.tar.bz2 &&
            tar xf asio-1.21.0.tar.bz2 &&
            cd asio-1.21.0 &&
            ./configure &&
            make &&
            make install &&
            cd ..
        CIBW_BEFORE_BUILD: >
          pip install Cython &&
          cmake -DOPENDHT_PYTHON=ON . &&
          make
      with:
        package-dir: python

    - uses: actions/upload-artifact@v2
      with:
        path: ./wheelhouse/*.whl

  publish:
    runs-on: ubuntu-latest
    needs: build_wheels
    steps:
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
