name: Python Package

on:
  release:
    types: [published]
  push:
  workflow_dispatch:


permissions:
  contents: read

jobs:
  build_wheels:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

      # You can run locally on any machine with docker using: pipx run cibuildwheel --platform linux python
    - name: Build wheels
      uses: pypa/cibuildwheel@v2.7.0
      with:
        package-dir: python

    - uses: actions/upload-artifact@v3
      with:
        name: opendht-wheels
        path: ./wheelhouse/*.whl

  publish:
    runs-on: ubuntu-latest
    needs: build_wheels
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: opendht-wheels
        path: dist

    - name: Publish package
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
