name: Python Package

on:
  release:
    types: [published]
  push:
  workflow_dispatch:


permissions:
  contents: read

jobs:
  build_wheels:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Stub `setup.py` check
      # It will be generated during CMake run
      # https://github.com/pypa/cibuildwheel/issues/1139
      run: touch python/setup.py

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.7.0
      env:
        CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_28
        CIBW_BEFORE_ALL: >
          dnf install -y cython3 &&
          cd python && cmake .
      with:
        package-dir: python

    - uses: actions/upload-artifact@v2
      with:
        path: ./wheelhouse/*.whl

  publish:
    runs-on: ubuntu-latest
    needs: build_wheels
    steps:
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
